apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: first-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-02-04T10:24:40Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    name: sushi-gateway-proxy
  name: sushi-gateway-proxy-deployment
  namespace: default
  resourceVersion: "108367"
  uid: 15c42c83-1446-40f6-9047-4e9c34889361
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: sushi-gateway-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: sushi-gateway-proxy
      name: sushi-gateway-proxy
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: sushi-config
        - secretRef:
            name: sushi-manager-secret
        image: rawsashimi/sushi-proxy:0.4.0
        imagePullPolicy: IfNotPresent
        name: sushi-gateway-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/config.json
          name: config-volume
          subPath: config.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: sushi-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-04T10:24:42Z"
    lastUpdateTime: "2025-02-04T10:24:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-04T10:24:40Z"
    lastUpdateTime: "2025-02-04T10:24:42Z"
    message: ReplicaSet "sushi-gateway-proxy-deployment-f97fb5fc9" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
