version: "3.8"

services:
  proxy:
    image: rawsashimi/sushi-proxy:latest
    ports:
      - "8008:8008"
      - "8443:8443"
    environment:
      - CONFIG_FILE_PATH=./app/gateway/gateway.json
      - SERVER_CERT_PATH=./app/gateway/server.crt
      - SERVER_KEY_PATH=./app/gateway/server.key
      - CA_CERT_PATH=./app/gateway/ca.crt
    volumes:
      - ./gateway/gateway.json:/app/gateway/gateway.json
      - ./gateway/server.crt:/app/gateway/server.crt
      - ./gateway/server.key:/app/gateway/server.key
      - ./gateway/ca.crt:/app/gateway/ca.crt