version: "3.8"

services:
  haproxy:
    container_name: haproxy-egress
    build:
      context: ./
      dockerfile: haproxy.Dockerfile
    ports:
      - "8092:80"
      - "8093:443"
      - "5555:5555"
#    volumes:
#      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  postgres:
    image: postgres:15-alpine
    depends_on:
      - haproxy
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sushi-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sushi-svc-1:
    image: rawsashimi/express-sushi-app
    ports:
      - "8001:3000"
    environment:
      - APP_ID=8001

  sushi-svc-2:
    image: rawsashimi/express-sushi-app
    ports:
      - "8002:3000"
    environment:
      - APP_ID=8002

volumes:
  postgres_data:
