version: "3.8"

services:
  sushi-svc-1:
    image: rawsashimi/express-sushi-app
    ports:
      - "8001:3000"
    environment:
      - APP_ID=8001
      - JWT_ISSUER=someIssuerKey
      - JWT_SECRET=123secret456

  sushi-svc-2:
    image: rawsashimi/express-sushi-app
    ports:
      - "8002:3000"
    environment:
      - APP_ID=8002
      - JWT_ISSUER=someIssuerKey
      - JWT_SECRET=123secret456
