global:
  name: sushi-gateway


image:
  sushi_proxy: 
    repository: rawsashimi/sushi-proxy
    tag: "0.4.0"
  sushi_manager: 
    repository: rawsashimi/sushi-manager
    tag: "0.4.0"


proxy:
  replicaCount: 1
  containers:
    ports:
      - containerPort: 8008
      - containerPort: 8081
      - containerPort: 8443

sushi_manager:
  replicaCount: 1
  containers:
    ports:
      containerPort: 5173


configMap:
  envName: sushi-env
  configFile: sushi-config


volumes:
  configVolumeName: config-volume
  mountPath: /app/config.json
  subPath: config.json

minikubeIp: 192.168.49.2
