apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-manager-deployment
  namespace: default
  labels:
    name: {{ .Values.global.name }}-manager
  annotations: 
      checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.image.sushi_manager.replicaCount }}
  selector:
      matchLabels:
        name: {{ .Values.global.name }}-manager
  template:
    metadata:
      name: {{ .Values.global.name }}-manager
      labels:
        name: {{ .Values.global.name }}-manager
    spec:
      containers:
        - name: {{ .Values.global.name }}-manager
          image: {{ .Values.image.sushi_manager.repository }}:{{ .Values.image.sushi_proxy.tag }}
          ports:
          - containerPort: {{ .Values.sushi_manager.containers.ports.containerPort }}
          env:
          - name: SUSHI_MANAGER_BACKEND_API_URL
            value: http://127.0.0.1:55240