name: Proxy Build
on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  build-proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        working-directory: ./sushi-proxy
        run: |
          go mod tidy
          go build -o sushi-proxy ./cmd

      - name: Run Tests
        env:
          SKIP_INTEGRATION_TESTS: true
        working-directory: ./sushi-proxy
        run: |
          go test -v ./...

      - name: Build Docker image
        working-directory: ./sushi-proxy
        run: |
          docker build -t sushi-proxy:ci-pipeline .
