name: Build and Push to Dockerhub

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  

      - name: Build
        run: |
          go mod tidy
          go build -o sushi-proxy ./sushi-proxy/cmd 

      - name: Run Tests
        run: |
          go test -v ./sushi-proxy/...

