name: CD

on:
  workflow_call:
    inputs:
      docker_tag:
        description: "Docker tag for the image"
        required: true
        type: string

jobs:
  deploy-manager-docker:
    uses: ./.github/workflows/deploy-manager.yml
    secrets: inherit
    with:
      docker_tag: ${{ inputs.docker_tag }}

  deploy-proxy-docker:
    uses: ./.github/workflows/deploy-proxy.yml
    secrets: inherit
    with:
      docker_tag: ${{ inputs.docker_tag }}

  deploy-docs:
    # We only want to deploy the docs when we PR to main
    secrets: inherit
    uses: ./.github/workflows/deploy-docs.yml
