name: Manager Deploy

on:
  workflow_call: # allow this workflow to be called from other workflows
    inputs:
      docker_tag:
        description: "Docker tag for the image"
        required: true
        type: string

jobs:
  deploy-docker-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: sushi-manager
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sushi-manager:${{ inputs.docker_tag }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sushi-manager:${{ inputs.docker_tag }}
