name: Deploy and Release new version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  determine-version:
    uses: ./.github/workflows/determine-version.yml
    with:
      branch_name: ${{ github.ref_name }}

  ci:
    uses: ./.github/workflows/ci.yml

  cd:
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    needs: [determine-version, ci]
    with:
      docker_tag: ${{ needs.determine-version.outputs.docker_tag }}

  release:
    uses: ./.github/workflows/release.yml
    # Only run this job when we push/PR to a release branch
    if: startsWith(github.ref, 'refs/heads/release/')
    needs: [determine-version, cd]
    with:
      release_tag: v${{ needs.determine-version.outputs.docker_tag }}
