# name: Sushi Proxy Build and Push to Dockerhub

# on:
#   push:
#     branches:
#       - main
#       - "release/*"
#   pull_request:
#     branches:
#       - main
#       - "release/*"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: "1.22"

#       - name: Build
#         working-directory: ./sushi-proxy
#         run: |
#           go mod tidy
#           go build -o sushi-proxy ./cmd

#       - name: Run Tests
#         env:
#           SKIP_INTEGRATION_TESTS: true
#         working-directory: ./sushi-proxy
#         run: |
#           go test -v ./...

#   deploy-docker:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Log in to Docker Hub
#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         working-directory: ./sushi-proxy
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/sushi-proxy:latest .

#       - name: Push Docker image
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/sushi-proxy:latest
